import Head from "next/head";
import styles from "../styles/globals.module.scss";
import Hero from "../components/Hero";
import Infos from "../components/Infos";
import Quizz from "../components/Quizz";
import Faq from "../components/Faq";
import Interview from "../components/Interview";

export default function Home() {
  return (
    <>
      <Head>
        <title>Entre gens</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <Hero />
        <Infos/>
        <Interview />
        <Quizz/>
        <Faq/>
      </div>
      <style jsx global>{`
        html {
          scroll-behavior: smooth;
          overflow-x: hidden;
        }

        body {
          margin: 0px;
          padding: 0px;
        }
        section:not(:first-of-type){
          padding: 100px 20px;
        }
      `}</style>
    </>
  )
}
