import Head from 'next/head'
import styles from '../styles/globals.module.scss'
import Header from '../components/Header'
import Reassurances from '../components/Reassurances'
import Faq from '../components/Faq'
import Quizz from '../components/Quizz'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Reassurances/>
      <Quizz/>
      <Faq/>
      <main className={styles.main}>
        <h1 className={styles.title}>Bonjour</h1>
      </main>
      <style jsx global>{`
        body {
          margin: 0px;
          padding: 0px;
        }
      `}</style>
    </div>
  )
}
